### ISSUE TITLE
CRX3 extension support, Debug option

### ISSUE THREAD

**Issue by rEnr3n** [xsmile/chromexup#10]
I have a problem installing HTTPS Everywhere.

`[WARNING] extension is not downloadable gcbommkclmclpchllfjekcdonpmejbdp`

I had this for weeks. I thought it was just a server issue. I tried to remove and reinstall. It's still not working.

EDIT: I just remembered I use adblocking. It could have been blocked by that. I just don't know what domain to whitelist. Can you add a debug option?

**Comment by xsmile** [comment]
The new CRX3 extension format caused the issue. These extensions require slightly different request parameters for the download URL. Version 0.5.1 should fix this.

Such an option already exists. You can use the `-v` parameter to increase output verbosity.

**Comment by rEnr3n** [comment]
It's working now on 0.5.1. Thank you.
