### ISSUE TITLE
Multiple profiles

### ISSUE THREAD

**Issue by rEnr3n** [xsmile/chromexup#2]
Does this work with the default profile only? I have three more profiles with different sets of extensions. I hope you could support them as well.

And thank you for this package.

**Comment by xsmile** [comment]
External extensions can be installed either system-wide in e.g. `/usr/share/chromium/extensions` or - as chromexup does it - for each user of the OS in e.g. `~/.config/chromium/External Extensions`, but not for each browser profile. As far as I know Chromium does not support it.

However, all such extensions will be usable by each browser profile and you can set them up independently.
