### ISSUE TITLE
Getting warning after removed extension was reinstated

### ISSUE THREAD

**Issue by rEnr3n** [xsmile/chromexup#8]
I have installed this extension https://chrome.google.com/webstore/detail/tabs-outliner/eggkanocgddhmamlbiijnphhppkpkmkl

One day, I got `[WARNING] extension is not downloadable eggkanocgddhmamlbiijnphhppkpkmkl`. It was not in the webstore anymore. I didn't remove it yet as I couldn't find an alternative. Days later, I can see the extension in the webstore. But I'm still getting the warning when running chromexup. It still has the same extension ID.

**Comment by xsmile** [comment]
Hi, this seems to be an issue with the web store. A test with an unmodified Chromium variant showed that the Tabs Outliner extension failed to download while other extensions worked fine.
My guess is that it might take a while for the extension to be fully available again.

**Comment by rEnr3n** [comment]
Warning is gone now.
