### ISSUE TITLE
Update extensions on more than one browser

### ISSUE THREAD

**Issue by rEnr3n** [xsmile/chromexup#9]
I have both inox and iridium installed on my linux. I want to update my extensions on both browsers at once. Something like this:

`branding = iridium, inox`

This would be enough for me since I want to have the same set of extensions in both browsers. For those who want separate set of extensions, additional config would be needed.

**Comment by xsmile** [comment]
Would a symbolic link to the `External Extensions` directory fit your needs instead?
```
ln -s ~/.config/inox/External\ Extensions/ ~/.config/iridium/
```

It would have the advantage of not having to download and store each extension twice.

**Comment by rEnr3n** [comment]
Right. How about for those that want different extensions in the other browser? I could put all extensions in the config and disable in each browser accordingly. But right now I'm having an issue with iridium. I can't disable any extension.

I could also link specific extensions but this is a hassle if the list is big. It's error-prone too. This is my only viable option right now. Hoping for an easier way.

**Comment by xsmile** [comment]
I'm not sure I understand the issue correctly. Two separate config files seem to be a good solution as you can configure extension sets which will be independent from each other.

Or do you want update all known extension sets for different browsers with one script run?
Currently you would need to run two commands (and optionally set up systemd services for them) like:
```
chromexup --cfgfile ~/.config/chromexup/config-inox.ini
chromexup --cfgfile ~/.config/chromexup/config-iridium.ini
```
In that case I can change the script to scan all `*.ini` files in the config directory when it runs.

By the way, I couldn't disable extensions with Iridium either when I used it.

**Comment by rEnr3n** [comment]
> In that case I can change the script to scan all *.ini files in the config directory when it runs.

This would be better.

**Comment by xsmile** [comment]
I added the change, please test if it is working for you.

**Comment by rEnr3n** [comment]
Working fine for me. Thanks.

**Comment by xsmile** [comment]
Nice :-)
